### ISSUE TITLE
[Bug] Connection event of the DELETE type is not sent after deletion connections with the Memif client

### ISSUE THREAD

**Issue by VitalyGushin** [networkservicemesh/cmd-nsc-vpp#629]
**Steps to reproduce:**
1. Connect to the MonitorConnections stream with an empty MonitorScopeSelector to catch all the connections, and listen to events (for all nsmgrs in the cluster)
2. Deploy any example with a **Memif client** (f.e. https://github.com/networkservicemesh/deployments-k8s/tree/release/v1.11.0/examples/use-cases/Memif2Kernel)
3. Cleanup the example from the step 2 by its namespace deletion (kubectl delete ns ns-memif2kernel). Also reproducible by pod deletion.

**Expected behaviour:** connection event of the DELETE type should be observed

**Observed behaviour:** no any connection events of the DELETE type (sometimes it will be sent after a few minutes of timeout)

**Comment by denis-tingaikin** [comment]
Seems like it's done.
